### PR TITLE
Collinbranch

### PR DESCRIPTION
**Pull request by collinwilliamson**

### CODE REVIEW

**Comment by collinwilliamson** [comment]
> Use markdown syntax. Html does not count :)

Updated to use syntax. I think I was able to make the right pull request, but I am not sure if you can see it or not.

**Comment by collinwilliamson** [comment]
@Kilavagora I think I created the right pull request. Should I merge?

**Comment by Kilavagora** [comment]
@colinwilliamson idea of me being added as collaborator was that I would approve it if everything was OK. So add me and I will approve the pull request :)

**Comment by Kilavagora** [comment]
Good!

**Pull request merged**
